All things

diff --git a/tools/testing/selftests/ftrace/ftracetest b/tools/testing/selftests/ftrace/ftracetest
--- a/tools/testing/selftests/ftrace/ftracetest
+++ b/tools/testing/selftests/ftrace/ftracetest
@@ -22,7 +22,6 @@ echo "		--fail-unresolved Treat UNRESOLVED as a failure"
 echo "		-d|--debug Debug mode (trace all shell commands)"
 echo "		-l|--logdir <dir> Save logs on the <dir>"
 echo "		            If <dir> is -, all logs output in console only"
-echo "		--rv       Run RV selftests instead of ftrace ones"
 exit $1
 }
 
@@ -130,12 +129,9 @@ parse_opts() { # opts
       shift 1
     ;;
     --logdir|-l)
-      USER_LOG_DIR=$2
+      LOG_DIR=$2
+      LINK_PTR=
       shift 2
-    ;;
-    --rv)
-      RV_TEST=1
-      shift 1
     ;;
     *.tc)
       if [ -f "$1" ]; then
@@ -156,12 +152,8 @@ parse_opts() { # opts
     ;;
     esac
   done
-  if [ -n "$OPT_TEST_CASES" ]; then
+  if [ ! -z "$OPT_TEST_CASES" ]; then
     TEST_CASES=$OPT_TEST_CASES
-  fi
-  if [ -n "$OPT_TEST_DIR" -a -f "$OPT_TEST_DIR"/test.d/functions ]; then
-    TOP_DIR=$OPT_TEST_DIR
-    TEST_DIR=$TOP_DIR/test.d
   fi
 }
 
@@ -198,7 +190,10 @@ fi
 TOP_DIR=`absdir $0`
 TEST_DIR=$TOP_DIR/test.d
 TEST_CASES=`find_testcases $TEST_DIR`
-USER_LOG_DIR=
+LOG_TOP_DIR=$TOP_DIR/logs
+LOG_DATE=`date +%Y%m%d-%H%M%S`
+LOG_DIR=$LOG_TOP_DIR/$LOG_DATE/
+LINK_PTR=$LOG_TOP_DIR/latest
 KEEP_LOG=0
 KTAP=0
 DEBUG=0
@@ -206,29 +201,14 @@ VERBOSE=0
 UNSUPPORTED_RESULT=0
 UNRESOLVED_RESULT=0
 STOP_FAILURE=0
-RV_TEST=0
 # Parse command-line options
 parse_opts $*
 
 [ $DEBUG -ne 0 ] && set -x
 
-# TOP_DIR can be changed for rv. Setting log directory.
-LOG_TOP_DIR=$TOP_DIR/logs
-LOG_DATE=`date +%Y%m%d-%H%M%S`
-if [ -n "$USER_LOG_DIR" ]; then
-  LOG_DIR=$USER_LOG_DIR
-  LINK_PTR=
-else
-  LOG_DIR=$LOG_TOP_DIR/$LOG_DATE/
-  LINK_PTR=$LOG_TOP_DIR/latest
-fi
-
-if [ $RV_TEST -ne 0 ]; then
-	TRACING_DIR=$TRACING_DIR/rv
-	if [ ! -d "$TRACING_DIR" ]; then
-		err_ret=$err_skip
-		errexit "rv is not configured in this kernel"
-	fi
+# Verify parameters
+if [ -z "$TRACING_DIR" -o ! -d "$TRACING_DIR" ]; then
+  errexit "No ftrace directory found"
 fi
 
 # Preparing logs
@@ -439,7 +419,7 @@ trap 'SIG_RESULT=$XFAIL' $SIG_XFAIL
 __run_test() { # testfile
   # setup PID and PPID, $$ is not updated.
   (cd $TRACING_DIR; read PID _ < /proc/self/stat; set -e; set -x;
-   checkreq $1; initialize_system; . $1)
+   checkreq $1; initialize_ftrace; . $1)
   [ $? -ne 0 ] && kill -s $SIG_FAIL $SIG_PID
 }
 
@@ -516,7 +496,7 @@ for t in $TEST_CASES; do
     exit 1
   fi
 done
-(cd $TRACING_DIR; finish_system) # for cleanup
+(cd $TRACING_DIR; finish_ftrace) # for cleanup
 
 prlog ""
 prlog "# of passed: " `echo $PASSED_CASES | wc -w`
